#!/usr/bin/dh-exec
debian/mm-hook => /usr/lib/x86_64-linux-gnu/ModemManager/fcc-unlock.d/14c3:4d75
debian/mm-hook => /usr/lib/x86_64-linux-gnu/ModemManager/fcc-unlock.d/8086:7560
debian/mm-hook => /usr/lib/x86_64-linux-gnu/ModemManager/fcc-unlock.d/1eac:1007
debian/mm-hook => /usr/lib/x86_64-linux-gnu/ModemManager/fcc-unlock.d/1eac:100d
debian/mm-hook => /usr/lib/x86_64-linux-gnu/ModemManager/fcc-unlock.d/2c7c:6008
DPR_Fcc_unlock_service /opt/fcc_lenovo/
libmodemauth.so /opt/fcc_lenovo/lib/
libmbimtools.so /opt/fcc_lenovo/lib/
debian/lenovo-fccunlock.service /lib/systemd/system/
